[package]
name = "egui-ssh-config"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.30"
egui = "0.30"
rfd = "0.15"
glob = "0.3"
dirs = "5.0"

[build-dependencies]
winresource = "0.1.23"
